class Language {
  String name;
  String localName;

  Language({required this.name, required this.localName});
}

class LanguageCode {
  // Map of language codes to language objects (name and localName)
  static Map<String, Language> languages = {
    'aa': Language(name: 'Afar', localName: 'Afar'),
    'ab': Language(name: 'Abkhazian', localName: 'Аҧсუ'),
    'ae': Language(name: 'Avestan', localName: 'Avesta'),
    'af': Language(name: 'Afrikaans', localName: 'Afrikaans'),
    'ak': Language(name: 'Akan', localName: 'Akan'),
    'am': Language(name: 'Amharic', localName: 'አማርኛ'),
    'an': Language(name: 'Aragonese', localName: 'Aragonés'),
    'ar': Language(name: 'Arabic', localName: 'العربية'),
    'as': Language(name: 'Assamese', localName: 'অসমীয়া'),
    'av': Language(name: 'Avaric', localName: 'Авар'),
    'ay': Language(name: 'Aymara', localName: 'Aymara'),
    'az': Language(name: 'Azerbaijani', localName: 'Azərbaycanca'),
    'ba': Language(name: 'Bashkir', localName: 'Башкир'),
    'be': Language(name: 'Belarusian', localName: 'Беларуская'),
    'bg': Language(name: 'Bulgarian', localName: 'Български'),
    'bh': Language(name: 'Bihari languages', localName: 'Bihari'),
    'bi': Language(name: 'Bislama', localName: 'Bislama'),
    'bm': Language(name: 'Bambara', localName: 'Bamanankan'),
    'bn': Language(name: 'Bengali', localName: 'বাংলা'),
    'bo': Language(name: 'Tibetan', localName: 'བོད་སྐད་'),
    'br': Language(name: 'Breton', localName: 'Brezhoneg'),
    'bs': Language(name: 'Bosnian', localName: 'Bosanski'),
    'ca': Language(name: 'Catalan; Valencian', localName: 'Català; Valencià'),
    'ce': Language(name: 'Chechen', localName: 'Нохчийн'),
    'ch': Language(name: 'Chamorro', localName: 'Chamoru'),
    'co': Language(name: 'Corsican', localName: 'Corsu'),
    'cr': Language(name: 'Cree', localName: 'ᓀᐦᑌᓐᓂ'),
    'cs': Language(name: 'Czech', localName: 'Čeština'),
    'cu': Language(name:'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', localName: 'Црковнославянский'),
    'cv': Language(name: 'Chuvash', localName: 'Чăваш'),
    'cy': Language(name: 'Welsh', localName: 'Cymraeg'),
    'da': Language(name: 'Danish', localName: 'Dansk'),
    'de': Language(name: 'German', localName: 'Deutsch'),
    'dv': Language(name: 'Divehi; Dhivehi; Maldivian', localName: 'ދިވެހި'),
    'dz': Language(name: 'Dzongkha', localName: 'རྫོང་ཁ'),
    'ee': Language(name: 'Ewe', localName: 'Eʋe'),
    'el': Language(name: 'Greek, Modern (1453-)', localName: 'Ελληνικά'),
    'en': Language(name: 'English', localName: 'English'),
    'eo': Language(name: 'Esperanto', localName: 'Esperanto'),
    'es': Language(name: 'Spanish; Castilian', localName: 'Español; Castellano'),
    'et': Language(name: 'Estonian', localName: 'Eesti keel'),
    'eu': Language(name: 'Basque', localName: 'Euskara'),
    'fa': Language(name: 'Persian', localName: 'فارسی'),
    'ff': Language(name: 'Fulah', localName: 'Fulah'),
    'fi': Language(name: 'Finnish', localName: 'Suomi'),
    'fj': Language(name: 'Fijian', localName: 'Na Vosa Vakaviti'),
    'fo': Language(name: 'Faroese', localName: 'Føroyskt'),
    'fr': Language(name: 'French', localName: 'Français'),
    'fy': Language(name: 'Western Frisian', localName: 'Frysk'),
    'ga': Language(name: 'Irish', localName: 'Gaeilge'),
    'gd': Language(name: 'Gaelic; Scottish Gaelic', localName: 'Gàidhlig'),
    'gl': Language(name: 'Galician', localName: 'Galego'),
    'gn': Language(name: 'Guarani', localName: 'Ava-guaraní'),
    'gu': Language(name: 'Gujarati', localName: 'ગુજરાતી'),
    'gv': Language(name: 'Manx', localName: 'Gaelg'),
    'ha': Language(name: 'Hausa', localName: 'Hausa'),
    'he': Language(name: 'Hebrew', localName: 'עברית'),
    'hi': Language(name: 'Hindi', localName: 'हिन्दी'),
    'ho': Language(name: 'Hiri Motu', localName: 'Hiri Motu'),
    'hr': Language(name: 'Croatian', localName: 'Hrvatski'),
    'ht': Language(name: 'Haitian; Haitian Creole', localName: 'Kreyòl Ayisyen'),
    'hu': Language(name: 'Hungarian', localName: 'Magyar'),
    'hy': Language(name: 'Armenian', localName: 'Հայերեն'),
    'hz': Language(name: 'Herero', localName: 'Otjiherero'),
    'ia': Language(name: 'Interlingua (International Auxiliary Language Association)', localName: 'Interlingua'),
    'id': Language(name: 'Indonesian', localName: 'Bahasa Indonesia'),
    'ie': Language(name: 'Interlingue; Occidental', localName: 'Interlingue'),
    'ig': Language(name: 'Igbo', localName: 'Igbo'),
    'ii': Language(name: 'Sichuan Yi; Nuosu', localName: 'ꆈꌠ꒿'),
    'ik': Language(name: 'Inupiaq', localName: 'Iñupiatun'),
    'io': Language(name: 'Ido', localName: 'Ido'),
    'is': Language(name: 'Icelandic', localName: 'Íslenska'),
    'it': Language(name: 'Italian', localName: 'Italiano'),
    'iu': Language(name: 'Inuktitut', localName: 'ᐃᓄᒃᑎᑐᑦ'),
    'ja': Language(name: 'Japanese', localName: '日本語'),
    'jv': Language(name: 'Javanese', localName: 'ꦧꦱꦗꦮ'),
    'ka': Language(name: 'Georgian', localName: 'ქართული'),
    'kg': Language(name: 'Kongo', localName: 'Kikongo'),
    'ki': Language(name: 'Kikuyu; Gikuyu', localName: 'Gĩkũyũ'),
    'kj': Language(name: 'Kuanyama; Kwanyama', localName: 'Kwanyama'),
    'kk': Language(name: 'Kazakh', localName: 'Қазақ тілі'),
    'kl': Language(name: 'Kalaallisut; Greenlandic', localName: 'Kalaallisut'),
    'km': Language(name: 'Central Khmer', localName: 'ភាសាខ្មែរ'),
    'kn': Language(name: 'Kannada', localName: 'ಕನ್ನಡ'),
    'ko': Language(name: 'Korean', localName: '한국어'),
    'kr': Language(name: 'Kanuri', localName: 'Kanuri'),
    'ks': Language(name: 'Kashmiri', localName: 'कश्मीरी'),
    'ku': Language(name: 'Kurdish', localName: 'Kurdî'),
    'kv': Language(name: 'Komi', localName: 'Коми'),
    'kw': Language(name: 'Cornish', localName: 'Kernewek'),
    'ky': Language(name: 'Kirghiz; Kyrgyz', localName: 'Кыргызча'),
    'la': Language(name: 'Latin', localName: 'Latina'),
    'lb': Language(name: 'Luxembourgish; Letzeburgesch', localName: 'Lëtzebuergesch'),
    'lg': Language(name: 'Ganda', localName: 'Luganda'),
    'li': Language(name: 'Limburgan; Limburger; Limburgish', localName: 'Limburgs'),
    'ln': Language(name: 'Lingala', localName: 'Lingála'),
    'lo': Language(name: 'Lao', localName: 'ລາວ'),
    'lt': Language(name: 'Lithuanian', localName: 'Lietuvių'),
    'lu': Language(name: 'Luba-Katanga', localName: 'Luba-Katanga'),
    'lv': Language(name: 'Latvian', localName: 'Latviešu'),
    'mg': Language(name: 'Malagasy', localName: 'Malagasy'),
    'mh': Language(name: 'Marshallese', localName: 'Kajin Majõl'),
    'mi': Language(name: 'Maori', localName: 'Māori'),
    'mk': Language(name: 'Macedonian', localName: 'Македонски'),
    'ml': Language(name: 'Malayalam', localName: 'മലയാളം'),
    'mn': Language(name: 'Mongolian', localName: 'Монгол'),
    'mr': Language(name: 'Marathi', localName: 'मराठी'),
    'ms': Language(name: 'Malay', localName: 'Bahasa Melayu'),
    'mt': Language(name: 'Maltese', localName: 'Malti'),
    'my': Language(name: 'Burmese', localName: 'ဗမာစာ'),
    'na': Language(name: 'Nauru', localName: 'Nauruan'),
    'nb': Language(name: 'Bokmål, Norwegian; Norwegian Bokmål', localName: 'Bokmål'),
    'nd': Language(name: 'Ndebele, North; North Ndebele', localName: 'Ndebele'),
    'ne': Language(name: 'Nepali', localName: 'नेपाली'),
    'ng': Language(name: 'Ndonga', localName: 'OshiNdonga'),
    'nl': Language(name: 'Dutch; Flemish', localName: 'Nederlands'),
    'nn': Language(name: 'Norwegian Nynorsk; Nynorsk, Norwegian', localName: 'Nynorsk'),
    'no': Language(name: 'Norwegian', localName: 'Norsk'),
    'nr': Language(name: 'Ndebele, South; South Ndebele', localName: 'isiNdebele'),
    'nv': Language(name: 'Navajo; Navaho', localName: 'Diné Bizaad'),
    'ny': Language(name: 'Chichewa; Chewa; Nyanja', localName: 'Chichewa'),
    'oc': Language(name: 'Occitan (post 1500)', localName: 'Occitan'),
    'oj': Language(name: 'Ojibwa', localName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ'),
    'om': Language(name: 'Oromo', localName: 'Oromoo'),
    'or': Language(name: 'Oriya', localName: 'ଓଡ଼ିଆ'),
    'os': Language(name: 'Ossetian; Ossetic', localName: 'Ирон'),
    'pa': Language(name: 'Panjabi; Punjabi', localName: 'ਪੰਜਾਬੀ'),
    'pi': Language(name: 'Pali', localName: 'पाली'),
    'pl': Language(name: 'Polish', localName: 'Polski'),
    'ps': Language(name: 'Pushto; Pashto', localName: 'پښتو'),
    'pt': Language(name: 'Portuguese', localName: 'Português'),
    'qu': Language(name: 'Quechua', localName: 'Runa Simi'),
    'rm': Language(name: 'Romansh', localName: 'Rumantsch'),
    'rn': Language(name: 'Rundi', localName: 'Kirundi'),
    'ro': Language(name: 'Romanian; Moldavian; Moldovan', localName: 'Română'),
    'ru': Language(name: 'Russian', localName: 'Русский'),
    'rw': Language(name: 'Kinyarwanda', localName: 'Kinyarwanda'),
    'sa': Language(name: 'Sanskrit', localName: 'संस्कृतम्'),
    'sc': Language(name: 'Sardinian', localName: 'Sardu'),
    'sd': Language(name: 'Sindhi', localName: 'سنڌي'),
    'se': Language(name: 'Northern Sami', localName: 'Davvisámegiella'),
    'sg': Language(name: 'Sango', localName: 'Sängö'),
    'si': Language(name: 'Sinhala; Sinhalese', localName: 'සිංහල'),
    'sk': Language(name: 'Slovak', localName: 'Slovenčina'),
    'sl': Language(name: 'Slovenian', localName: 'Slovenščina'),
    'sm': Language(name: 'Samoan', localName: 'Gagana Samoa'),
    'sn': Language(name: 'Shona', localName: 'ChiShona'),
    'so': Language(name: 'Somali', localName: 'Soomaali'),
    'sq': Language(name: 'Albanian', localName: 'Shqip'),
    'sr': Language(name: 'Serbian', localName: 'Српски'),
    'ss': Language(name: 'Swati', localName: 'SiSwati'),
    'st': Language(name: 'Sotho, Southern', localName: 'Sesotho'),
    'su': Language(name: 'Sundanese', localName: 'Basa Sunda'),
    'sv': Language(name: 'Swedish', localName: 'Svenska'),
    'sw': Language(name: 'Swahili', localName: 'Kiswahili'),
    'ta': Language(name: 'Tamil', localName: 'தமிழ்'),
    'te': Language(name: 'Telugu', localName: 'తెలుగు'),
    'tg': Language(name: 'Tajik', localName: 'Тоҷикӣ'),
    'th': Language(name: 'Thai', localName: 'ไทย'),
    'ti': Language(name: 'Tigrinya', localName: 'ትግርኛ'),
    'tk': Language(name: 'Turkmen', localName: 'Türkmen'),
    'tl': Language(name: 'Tagalog', localName: 'Tagalog'),
    'tn': Language(name: 'Tswana', localName: 'Setswana'),
    'to': Language(name: 'Tonga (Tonga Islands)', localName: 'Lea Faka-Tonga'),
    'tr': Language(name: 'Turkish', localName: 'Türkçe'),
    'ts': Language(name: 'Tsonga', localName: 'Xitsonga'),
    'tt': Language(name: 'Tatar', localName: 'Татар теле'),
    'tw': Language(name: 'Twi', localName: 'Twi'),
    'ty': Language(name: 'Tahitian', localName: 'Reo Tahiti'),
    'ug': Language(name: 'Uighur; Uyghur', localName: 'ئۇيغۇرچە'),
    'uk': Language(name: 'Ukrainian', localName: 'Українська'),
    'ur': Language(name: 'Urdu', localName: 'اردو'),
    'uz': Language(name: 'Uzbek', localName: 'O‘zbek'),
    've': Language(name: 'Venda', localName: 'Tshivenḓa'),
    'vi': Language(name: 'Vietnamese', localName: 'Tiếng Việt'),
    'vo': Language(name: 'Volapük', localName: 'Volapük'),
    'wa': Language(name: 'Walloon', localName: 'Walon'),
    'wo': Language(name: 'Wolof', localName: 'Wolof'),
    'xh': Language(name: 'Xhosa', localName: 'isiXhosa'),
    'yi': Language(name: 'Yiddish', localName: 'ייִדיש'),
    'yo': Language(name: 'Yoruba', localName: 'Yorùbá'),
    'za': Language(name: 'Zhuang; Chuang', localName: 'Vahcuengh'),
    'zh': Language(name: 'Chinese', localName: '中文'),
    'zu': Language(name: 'Zulu', localName: 'isiZulu')
  };

  // Get language object for the given language code
  static Language getName(String languageCode) {
    return languages[languageCode] ??
        Language(
          name: languageCode.toUpperCase(),
          localName: languageCode.toUpperCase(),
        );
  }
}
